version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cly-todo-backend
    expose:
      - "8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - todo-network

  nginx:
    build:
      context: ./_nginx
      dockerfile: Dockerfile
    container_name: cly-todo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - nginx_logs:/var/log/nginx
    env_file:
      - ./_nginx/.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - todo-network

volumes:
  certbot_conf:
  certbot_www:
  nginx_logs:

networks:
  todo-network:
    driver: bridge
